### PR TITLE
add heading converter to htmltomd

### PR DESCRIPTION
**Pull request by Karthick47v2**
- Added a new function `custom_make_translation` which makes it easy to replace multiple string to multiple strings at once.
- Added html to md conversion for heading

### CODE REVIEW

**Comment by Karthick47v2** [comment]
- Added md to html conversion for heading
- Changed read whole data and write whole data fashion into read and write line by line.

Processing line by line makes it easy to convert to tags

**Comment by prakhartiwari0** [comment]
Good Job!

**Comment by prakhartiwari0** [comment]
I am thinking to shift to a web app instead of the terminal app. Or can we just start a new project for the web version and keep this terminal version as it is, I just want to know your opinion.

**Comment by Karthick47v2** [comment]
Yeah, web application would be easy to use for users. And I found that every time we need to working with terminal, put text into input.txt and then again work with terminal, which would be frustrating and time-consuming in testing (from developer side of view).

**Comment by prakhartiwari0** [comment]
> Yeah, web application would be easy to use for users. And I found that every time we need to working with terminal, put text into input.txt and then again work with terminal, which would be frustrating and time-consuming in testing (from developer side of view).

Great! Then I am going to abandon this project, it will still be open for anybody who wants to contribute to Python language, but I will mention that this project's purpose is now fulfilled by another Web project, and therefore this project is inactive.
Or should I make it read-only and not accept contributions?

**Comment by prakhartiwari0** [comment]
Because anyways the logic will be the same, an only the programming language will be different, we developers are basically problem-solvers so it is nothing of a big deal.

**Comment by Karthick47v2** [comment]
@prakhartiwari0 I think making it available to contributions would be great as, still, the web application needs to be developed from scratch (as of now, only heading function is fully working on both sides). So, it would be easy if new contributions to this repo brings effective algorithms/ideas.

**Comment by prakhartiwari0** [comment]
> @prakhartiwari0 I think making it available to contributions would be great as, still, the web application needs to be developed from scratch (as of now, only heading function is fully working on both sides). So, it would be easy if new contributions to this repo brings effective algorithms/ideas.

Sure, I will plan for the Web Project whenever I get time.
**Thanks for helping me** with decision-making, I am **glad** to have you as a contributor (+ a little mentor).
Currently, I am busy with **[Arito](https://github.com/prakhartiwari0/arito)**...
I would be really grateful if you check it out and share your feedback on [ProductHunt](https://www.producthunt.com/posts/arito)

**Pull request merged**
